Move go-client to EC
Edge-Center/edgecentercloud-go pull request #1
Opened 2022-12-20 07:59 UTC by MoonNight131

Go test 98% OK.
Locally test go-client is ok.

2022-12-21 09:28 UTC, alex2304 commented
В faas, ddos и heat ты не стал менять, потому что будем удалять их, наверное. Про faas и ddos верно, а вот heat мы оставляем, там нужно поменять.

Вот что ещё осталось: `ReadGcoreError`, `GcoreErrorType`, и другие места (Cmd+Shift+F в Goland -- поиск по проекту)

2022-12-21 09:30 UTC, alex2304 requested changes
Осталось поправить где осталось "gcore" (помимо faas и ddos)

Также прошу прикрепить вывод упавших тестов, или хотя бы их названия. Надо посмотреть, можем ли мы сказать, что это точно не из-за переименований и также смены версии go с 1.16 на 1.19

2022-12-21 16:27 UTC, MoonNight131 commented
```
=== RUN   TestList
    requests_test.go:53: 
        	Error Trace:	requests_test.go:53
        	            				pager.go:116
        	            				requests_test.go:48
        	Error:      	Not equal: 
        	            	expected: floatingips.FloatingIPDetail{FloatingIPAddress:net.IP(nil), RouterID:"", SubnetID:"", Status:"", ID:"", PortID:"", DNSDomain:"", DNSName:"", FixedIPAddress:net.IP(nil), UpdatedAt:<nil>, CreatedAt:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), CreatorTaskID:(*string)(nil), ProjectID:0, RegionID:0, Region:"", Instance:instances.Instance{ID:"a7e7e8d6-0bf7-4ac9-8170-831b47ee2ba9", Name:"Testing", Description:"Testing", CreatedAt:time.Date(2019, time.July, 11, 6, 58, 48, 0, time.UTC), Status:"ACTIVE", VMState:"active", TaskState:(*string)(nil), Flavor:flavors.Flavor{FlavorID:"", FlavorName:"", PriceStatus:(*string)(nil), CurrencyCode:(*edgecloud.Currency)(nil), PricePerHour:(*decimal.Decimal)(nil), PricePerMonth:(*decimal.Decimal)(nil), RAM:0, VCPUS:0}, Metadata:map[string]interface {}{"task_id":"d1e1500b-e2be-40aa-9a4b-cc493fa1af30"}, Volumes:[]instances.InstanceVolume{instances.InstanceVolume{ID:"28bfe198-a003-4283-8dca-ab5da4a71b62", DeleteOnTermination:false}}, Addresses:map[string][]instances.InstanceAddress(nil), SecurityGroups:[]edgecloud.ItemName(nil), CreatorTaskID:(*string)(nil), TaskID:(*string)(nil), ProjectID:1, RegionID:1, Region:"ED-8", AvailabilityZone:"nova"}}
        	            	actual  : floatingips.FloatingIPDetail{FloatingIPAddress:net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff, 0xff, 0xac, 0x18, 0x4, 0x22}, RouterID:"11005a33-c5ac-4c96-ab6f-8f2827cc7da6", SubnetID:"", Status:"ACTIVE", ID:"c64e5db1-5f1f-43ec-a8d9-5090df85b82d", PortID:"ee2402d0-f0cd-4503-9b75-69be1d11c5f1", DNSDomain:"", DNSName:"", FixedIPAddress:net.IP(nil), UpdatedAt:time.Date(2019, time.June, 13, 13, 58, 12, 0, time.Location("")), CreatedAt:time.Date(2019, time.June, 13, 13, 58, 12, 0, time.Location("")), CreatorTaskID:(*string)(nil), ProjectID:1, RegionID:1, Region:"ED-8", Instance:instances.Instance{ID:"a7e7e8d6-0bf7-4ac9-8170-831b47ee2ba9", Name:"Testing", Description:"Testing", CreatedAt:time.Date(2019, time.July, 11, 6, 58, 48, 0, time.UTC), Status:"ACTIVE", VMState:"active", TaskState:(*string)(nil), Flavor:flavors.Flavor{FlavorID:"", FlavorName:"", PriceStatus:(*string)(nil), CurrencyCode:(*edgecloud.Currency)(nil), PricePerHour:(*decimal.Decimal)(nil), PricePerMonth:(*decimal.Decimal)(nil), RAM:0, VCPUS:0}, Metadata:map[string]interface {}{"task_id":"d1e1500b-e2be-40aa-9a4b-cc493fa1af30"}, Volumes:[]instances.InstanceVolume{instances.InstanceVolume{ID:"28bfe198-a003-4283-8dca-ab5da4a71b62", DeleteOnTermination:false}}, Addresses:map[string][]instances.InstanceAddress(nil), SecurityGroups:[]edgecloud.ItemName(nil), CreatorTaskID:(*string)(nil), TaskID:(*string)(nil), ProjectID:1, RegionID:1, Region:"ED-8", AvailabilityZone:"nova"}}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,8 +1,8 @@
        	            	 (floatingips.FloatingIPDetail) {
        	            	- FloatingIPAddress: (net.IP) <nil>,
        	            	- RouterID: (string) "",
        	            	+ FloatingIPAddress: (net.IP) (len=16) 172.24.4.34,
        	            	+ RouterID: (string) (len=36) "11005a33-c5ac-4c96-ab6f-8f2827cc7da6",
        	            	  SubnetID: (string) "",
        	            	- Status: (string) "",
        	            	- ID: (string) "",
        	            	- PortID: (string) "",
        	            	+ Status: (string) (len=6) "ACTIVE",
        	            	+ ID: (string) (len=36) "c64e5db1-5f1f-43ec-a8d9-5090df85b82d",
        	            	+ PortID: (string) (len=36) "ee2402d0-f0cd-4503-9b75-69be1d11c5f1",
        	            	  DNSDomain: (string) "",
        	            	@@ -10,8 +10,8 @@
        	            	  FixedIPAddress: (net.IP) <nil>,
        	            	- UpdatedAt: (*edgecloud.JSONRFC3339Z)(<nil>),
        	            	- CreatedAt: (edgecloud.JSONRFC3339Z) 0001-01-01 00:00:00 +0000 UTC,
        	            	+ UpdatedAt: (*edgecloud.JSONRFC3339Z)(2019-06-13 13:58:12 +0000 +0000),
        	            	+ CreatedAt: (edgecloud.JSONRFC3339Z) 2019-06-13 13:58:12 +0000 +0000,
        	            	  CreatorTaskID: (*string)(<nil>),
        	            	- ProjectID: (int) 0,
        	            	- RegionID: (int) 0,
        	            	- Region: (string) "",
        	            	+ ProjectID: (int) 1,
        	            	+ RegionID: (int) 1,
        	            	+ Region: (string) (len=4) "ED-8",
        	            	  Instance: (instances.Instance) {
        	Test:       	TestList
--- FAIL: TestList (0.00s)
=== RUN   TestListAll
    requests_test.go:86: 
        	Error Trace:	requests_test.go:86
        	Error:      	Not equal: 
        	            	expected: floatingips.FloatingIPDetail{FloatingIPAddress:net.IP(nil), RouterID:"", SubnetID:"", Status:"", ID:"", PortID:"", DNSDomain:"", DNSName:"", FixedIPAddress:net.IP(nil), UpdatedAt:<nil>, CreatedAt:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), CreatorTaskID:(*string)(nil), ProjectID:0, RegionID:0, Region:"", Instance:instances.Instance{ID:"a7e7e8d6-0bf7-4ac9-8170-831b47ee2ba9", Name:"Testing", Description:"Testing", CreatedAt:time.Date(2019, time.July, 11, 6, 58, 48, 0, time.UTC), Status:"ACTIVE", VMState:"active", TaskState:(*string)(nil), Flavor:flavors.Flavor{FlavorID:"", FlavorName:"", PriceStatus:(*string)(nil), CurrencyCode:(*edgecloud.Currency)(nil), PricePerHour:(*decimal.Decimal)(nil), PricePerMonth:(*decimal.Decimal)(nil), RAM:0, VCPUS:0}, Metadata:map[string]interface {}{"task_id":"d1e1500b-e2be-40aa-9a4b-cc493fa1af30"}, Volumes:[]instances.InstanceVolume{instances.InstanceVolume{ID:"28bfe198-a003-4283-8dca-ab5da4a71b62", DeleteOnTermination:false}}, Addresses:map[string][]instances.InstanceAddress(nil), SecurityGroups:[]edgecloud.ItemName(nil), CreatorTaskID:(*string)(nil), TaskID:(*string)(nil), ProjectID:1, RegionID:1, Region:"ED-8", AvailabilityZone:"nova"}}
        	            	actual  : floatingips.FloatingIPDetail{FloatingIPAddress:net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff, 0xff, 0xac, 0x18, 0x4, 0x22}, RouterID:"11005a33-c5ac-4c96-ab6f-8f2827cc7da6", SubnetID:"", Status:"ACTIVE", ID:"c64e5db1-5f1f-43ec-a8d9-5090df85b82d", PortID:"ee2402d0-f0cd-4503-9b75-69be1d11c5f1", DNSDomain:"", DNSName:"", FixedIPAddress:net.IP(nil), UpdatedAt:time.Date(2019, time.June, 13, 13, 58, 12, 0, time.Location("")), CreatedAt:time.Date(2019, time.June, 13, 13, 58, 12, 0, time.Location("")), CreatorTaskID:(*string)(nil), ProjectID:1, RegionID:1, Region:"ED-8", Instance:instances.Instance{ID:"a7e7e8d6-0bf7-4ac9-8170-831b47ee2ba9", Name:"Testing", Description:"Testing", CreatedAt:time.Date(2019, time.July, 11, 6, 58, 48, 0, time.UTC), Status:"ACTIVE", VMState:"active", TaskState:(*string)(nil), Flavor:flavors.Flavor{FlavorID:"", FlavorName:"", PriceStatus:(*string)(nil), CurrencyCode:(*edgecloud.Currency)(nil), PricePerHour:(*decimal.Decimal)(nil), PricePerMonth:(*decimal.Decimal)(nil), RAM:0, VCPUS:0}, Metadata:map[string]interface {}{"task_id":"d1e1500b-e2be-40aa-9a4b-cc493fa1af30"}, Volumes:[]instances.InstanceVolume{instances.InstanceVolume{ID:"28bfe198-a003-4283-8dca-ab5da4a71b62", DeleteOnTermination:false}}, Addresses:map[string][]instances.InstanceAddress(nil), SecurityGroups:[]edgecloud.ItemName(nil), CreatorTaskID:(*string)(nil), TaskID:(*string)(nil), ProjectID:1, RegionID:1, Region:"ED-8", AvailabilityZone:"nova"}}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,8 +1,8 @@
        	            	 (floatingips.FloatingIPDetail) {
        	            	- FloatingIPAddress: (net.IP) <nil>,
        	            	- RouterID: (string) "",
        	            	+ FloatingIPAddress: (net.IP) (le [...]

2022-12-25 22:34 UTC, alex2304 commented
LGTM 👍 

По тестам кажется всё ок. Если правильно прочитал, их всего 3 упавших, и все 3 похожи на ошибку в логике, и не связаны с изменением версии языка.

Вижу ещё, что ты менял makefile, видимо тоже какие-то проблемы были? Удалось всё поправить?

Аппрув поставил

2022-12-25 22:34 UTC, alex2304 approved these changes

2022-12-26 07:18 UTC, MoonNight131 commented
> Вижу ещё, что ты менял makefile, видимо тоже какие-то проблемы были? Удалось всё поправить?
Там не то чтобы большие проблемы. Но в целом да, удалось

2022-12-26 07:18 UTC, merged