Cloud 318 refactoring
Edge-Center/edgecentercloud-go pull request #5
Opened 2023-03-28 20:05 UTC by anaxaim

2023-03-30 15:00 UTC, alex2304 commented on Makefile
> +export VAULT_ADDR = https://vault.p.ecnl.ru/
либо второй вариант - вынести в энв файл, где указываются остальные эдж центровские адреса

2023-03-30 15:04 UTC, alex2304 commented on Makefile
> +local_tests: envs_reader
nit: `run_local_tests`

2023-03-31 06:26 UTC, anaxaim commented on .gitignore
> +vault
они в Makefile генерятся для локальных тестов и кладутся в корень, добавил чтобы случайно не занести

2023-03-31 06:28 UTC, anaxaim commented on .golangci.yml
> +    # skip
если верхние линтеры убраны так как они устарели, то те которые # skip  - скипнул, так как они спорные и портят код-стайл

2023-03-31 06:30 UTC, anaxaim commented on .golangci.yml
> +    # complexity: need to refactor
да, ко всем линтерам ниже коммита. это линтеры про сложность методов и функций. по-хорошему их надо поправить, но это не просто, долго и можно логику сломать. когда-нибудь вернусь к ним

2023-03-31 06:38 UTC, anaxaim commented on .gitignore
> +bin/golangci-lint
добавил и перенес jq и vault туда же, поэтому убрал их из gitignore

2023-03-31 06:39 UTC, anaxaim commented on .gitignore
> +vault
убрал, бинарники теперь генерю в папку bin, которую заигнорил

2023-03-31 06:52 UTC, anaxaim commented on Makefile
> +export VAULT_ADDR = https://vault.p.ecnl.ru/
выбрал второй вариант

2023-03-31 06:54 UTC, anaxaim commented on .env
> +EC_CLOUD_PROJECT=217086
для локальных тестов должен наполняться из vault. для тестов в гитхабе эти энвы берутся из секретов, потому что вольт во внутренней сети edgecenter

2023-04-04 09:54 UTC, alex2304 commented on .env
> +EC_CLOUD_PROJECT=217086
обычно энв файлы просто не кладут в репозиторий, они создаются локально при каких-либо действиях с кодом

как вариант -- .env файл с адресами можно сгенерить баш-скриптом при запуске тестов, по типу 
```bash
echo "EC_CLOUD_API_URL=https://api.edgecenter.ru/cloud
EC_CLOUD_AUTH_URL=https://api.edgecenter.ru
VAULT_ADDR=https://vault.p.ecnl.ru/" > .env
```

2023-04-04 10:08 UTC, alex2304 requested changes
Есть еще одно улучшение

Обычно .env файлы не добавляют в отслеживание, потому что ты там часто что-то меняешь, и это тебе будет мешать при работе с git (каждый раз будет измененный файл).

Вот что можно сделать:
- удалить .env из репозитория, добавить его в .gitignore
- в команде `download_env_file` первым шагом генерировать текущее содержимое `.env` файла через `echo "..." > .env`
- В makefile инструкцию `export VAULT_ADDR=...` внести внутрь команды `download_env_file`, потому что в других командах не используется
- в команде `download_env_file` содержимым из vault дополнять файл: `vault ... >> .env`

Таким образом, у тебя при вызове `download_env_file` будет создаваться локальный не отслеживаемый .env файл, это подойдет для ci/cd и для разработчиков. Разработчики смогут менять там адреса для переключения прод/препрод, и это не будет мешать им при работе с гитом.

2023-04-05 07:27 UTC, alex2304 approved these changes

2023-04-05 07:34 UTC, merged